config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "main#index"

    get 'about-us', to: 'about#index', as: :about

    get 'password', to: 'passwords#edit', as: :edit_password
    patch 'password', to: 'passwords#update'

    get 'forgot_password', to: 'password_resets#new'
    post 'forgot_password', to: 'password_resets#create'
    get 'forgot_password/edit', to: 'password_resets#edit'
    patch 'forgot_password/edit', to: 'password_resets#update'

    get 'sign_up', to: 'registrations#new'
    post 'sign_up', to: 'registrations#create'

    get 'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user

    def user=(user)
        super
    end
end

app/models/user.rb
#email:string 
#password_digest:string
#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'must be a valid email'}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be logged in!" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If you have account with us a password reset link has been sent to your email."
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: 'password reset')
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to sign_in_path, alert: "Expired link. Please try again."
    end

    def update
        @user = User.find_signed(params[:token], purpose: 'password reset')
        if @user.update(password_params)
            redirect_to root_path, notice: "Password reset successfully"
        else
            render :edit, status: 422
        end 
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end 
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "password updated"
        else
            render :edit, status: 422
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Sign up successful"
        else
            render :new, status: 422
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if(user.present? && user.authenticate(params[:password]))
            session[:user_id] = user.id
            redirect_to root_path, notice: "log in succesful"
        else
            flash[:alert] = "invalid email or password"
            render :new, status: 422
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logout successful'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySimpleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
        <%= render partial: "shared/flash" %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to My Simple App</h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset Your passowrd</h1>

<%= form_with model: @user, url: forgot_password_edit_path(token: params[:token]) do |form|  %>

    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div>
                    <%= message %>
                </div>
            <% end %>
        </div>
    <% end %>
    
     <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-outline-success" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your passowrd</h1>

<%= form_with url: forgot_password_path do |form|  %>

    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "user@gin.com" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Submit", class: "btn btn-outline-success" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "My Simple App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
            </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if Current.user %>
                <li class="nav-item">
                    <%= link_to Current.user.email, edit_password_path, class: 'nav-link' %></span>
                </li>
                <li class="nav-item">
                    <%= button_to "Log out", logout_path, method: :delete, class: 'nav-link btn btn-info mt-2' %>
                </li>

            <% else %>
                <li class="nav-item">
                    <%= link_to "Login", sign_in_path, class: 'nav-link' %>

                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", sign_up_path, class: 'nav-link' %>
                </li>

            <% end %>
        </ul>
    </div>
  </div>
</nav>